const CANVAS_HEIGHT = 500;
const CANVAS_WIDTH = 500;

const N_SHEEP = 20;
const CIRCLE_SIZE = 20;

const SHEEP_SIGHT_FOR_DOG = 150;
const SHEEP_SIGHT_FOR_OTHER_SHEEP = 150;

const SHEEP_VELOCITY_MULT = 0.01;
const DOG_VELOCITY_MULT = 0.01;

const FRAME_RATE = 30;
